# Generated by Django 5.0 on 2023-12-13 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creditapi', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='current_debt',
            new_name='age',
        ),
        migrations.AlterField(
            model_name='customer',
            name='approved_limit',
            field=models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=10, null=True),
        ),
    ]
