# Generated by Django 5.0 on 2023-12-13 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('creditapi', '0003_rename_customer_loan_customer_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='loan',
            old_name='customer_id',
            new_name='customer',
        ),
    ]
